# Generated by Django 4.1 on 2022-08-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_count',
        ),
    ]
