# Generated by Django 4.1 on 2022-08-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_1',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
