# Generated by Django 4.1 on 2022-08-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_rename_title_1_post_title_name_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_name_1',
            new_name='name_1',
        ),
    ]
