# Generated by Django 4.1 on 2022-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_rename_title_name_1_post_name_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_2',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_3',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_4',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_5',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_6',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
